### ISSUE TITLE
what about image in word doc

### ISSUE THREAD

**Issue by nosun** [cigzigwon/DocX2HtmlParser#1]

**Comment by cigzigwon** [comment]
I did not add this feature yet. As a web developer I use this to import docx files as an initial draft for web content in a CMS. Since no user ever has an image that I can use... I just manually add them later because our design team finds acceptable/safe images to publish. You could just try adding that support on your own but eventually I will be adding that and re-writing the code into PSR4 with interfaces to handle all types of document imports such as .odt as well. I don't plan on accepting PR until I perform the overhaul simply because I want a better class design so others can adhere to a standard. You can submit a PR if you'd like!

**Comment by nosun** [comment]
I see, Thanks very much!
