### ISSUE TITLE
whole html code is intended in same line

### ISSUE THREAD

**Issue by gouravmalviya0** [cigzigwon/DocX2HtmlParser#3]
It is working nice but whole code of html comes in same line. How that code can be make clearly understandable

**Comment by cigzigwon** [comment]
Send it's output to a library that pretty prints. The parser is intended to parse and it's output is a textual blob because those are ideal for storage. I use this in my CMS to create new webpages based on a word document upload. I tend to support more document types but pretty printing is a feature that will not be added because it is not the focus of work here, just wrap the class with something that does.

**Comment by cigzigwon** [comment]
If you are using it to quickly start development of a static page. Just insert the output here: https://www.10bestdesign.com/dirtymarkup/

**Comment by gouravmalviya0** [comment]
thank you your code helped me a lot
